name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - develop # Deploy to dev on pushes to the 'develop' branch
      - main # Deploy to staging on pushes to the 'main' branch
    tags:
      - 'v*' # Deploy to production on pushes with tags starting with 'v'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Firebase CLI (Dev)
        if: github.ref == 'refs/heads/develop'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MINIMAL_DEV_14F70 }} # Dev project secret
          channelId: live
          projectId: minimal-dev-14f70 # Dev project ID
      - name: Set up Firebase CLI (Staging)
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MINIMAL_STAG }} # Staging project secret
          channelId: live
          projectId: minimal-stag # Staging project ID
      - name: Deploy to Production (if tagged)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MINIMAL_PROD }} # Production project secret
          channelId: live
          projectId: minimal-prod # Production project ID
